document.writeln("            ");
document.writeln("  <!--MAIN NAVIGATION-->");
document.writeln("  <!--===================================================-->");
document.writeln("  <nav id=\'mainnav-container\'>");
document.writeln("      <div id=\'mainnav\'>");
document.writeln("  ");
document.writeln("          <!--Menu-->");
document.writeln("          <!--================================-->");
document.writeln("          <div id=\'mainnav-menu-wrap\'>");
document.writeln("              <div class=\'nano\'>");
document.writeln("                  <div class=\'nano-content\'>");
document.writeln("  ");
document.writeln("                      <ul id=\'mainnav-menu\' class=\'list-group\'>");
document.writeln("  			");
document.writeln("                          <!--Category name-->");
document.writeln("  			            <li class=\'list-header\'><font size=\'4\'>Network</font></li>");
document.writeln("  ");
document.writeln("  						<li>");
document.writeln("  						     <a href=\'./cit.html\'>");
document.writeln("  						         <i class=\'fa fa-search\' style=\'width:24px\'></i>");
document.writeln("  						         <span class=\'menu-title\'>");
document.writeln("  						            <font size=\'3\'> <strong>Citation</strong></font>");
document.writeln("  						         </span>");
document.writeln("  						         ");
document.writeln("  						     </a>");
document.writeln("  						                             ");
document.writeln("  						 </li>");
document.writeln("  						 ");
document.writeln("  						 <li>");
document.writeln("  						      <a href=\'./co-cit.html\'>");
document.writeln("  						          <i class=\'fa fa-search\' style=\'width:24px\'></i>");
document.writeln("  						          <span class=\'menu-title\'>");
document.writeln("  						              <font size=\'3\'><strong>Co-Citation</strong></font>");
document.writeln("  						          </span>");
document.writeln("  						          ");
document.writeln("  						      </a>");
document.writeln("  						                              ");
document.writeln("  						  </li>");
document.writeln("  						  ");
document.writeln("  						  <li>");
document.writeln("  						       <a href=\'./co-be-cit.html\'>");
document.writeln("  						           <i class=\'fa fa-search\' style=\'width:24px\'></i>");
document.writeln("  						           <span class=\'menu-title\'>");
document.writeln("  						             <font size=\'3\'><strong>Co-Cited</strong></font>");
document.writeln("  						           </span>");
document.writeln("  						           ");
document.writeln("  						       </a>");
document.writeln("  						                               ");
document.writeln("  						   </li>    ");
document.writeln("  ");
document.writeln("  					   <!--Menu list item-->");
document.writeln("  		   ");
document.writeln("  						");
document.writeln("  						<li>");
document.writeln("  						    <a href=\'./co-author.html\'>");
document.writeln("  						        <i class=\'fa fa-pie-chart\' style=\'width:24px\'></i>");
document.writeln("  						        <span class=\'menu-title\'>");
document.writeln("  						            <font size=\'3\'><strong>Co-Authorship</strong></font>");
document.writeln("  						        </span>");
document.writeln("  						        ");
document.writeln("  						    </a>");
document.writeln("  						                        ");
document.writeln("  						</li>");
document.writeln("  						");

document.writeln("  						    <a href=\'./domain.html\'>");
document.writeln("  						        <i class=\'fa fa-pie-chart\' style=\'width:24px\'></i>");
document.writeln("  						        <span class=\'menu-title\'>");
document.writeln("  						            <font size=\'3\'><strong>Subject Citation</strong></font>");
document.writeln("  						        </span>");
document.writeln("  						    </a>                     ");
document.writeln("  						</li>");


document.writeln("  						<li class=\'list-divider\'></li>");
document.writeln("  						");
document.writeln("  			            <!--Category name-->");
document.writeln("  			            <li class=\'list-header\'><font size=\'4\'>Searching System</font></li>");
document.writeln("  			");
document.writeln("  			            <!--Menu list item-->");
document.writeln("  			            <li>");
document.writeln("  			                <a href=\'./query_author.html\'>");
document.writeln("  			                    <i class=\'fa fa-question-circle\' style=\'width:24px\'></i>");
document.writeln("  			                    <font size=\'3\'><b>Search Authors</b></font>	");
document.writeln("  			                </a>");
document.writeln("  							");
document.writeln("  			            </li>");
document.writeln("  						");
document.writeln("  						<!--Menu list item-->");
document.writeln("  						<li>");
document.writeln("  						    <a href=\'./query_paper.html\'>");
document.writeln("  						        <i class=\'fa fa-question-circle\' style=\'width:24px\'></i>");
document.writeln("  						        <font size=\'3\'><b>Search Papers</b></font>");
document.writeln("  						    </a>");
document.writeln("  							");
document.writeln("  						</li>");



document.writeln("  						<li class=\'list-divider\'></li>");
document.writeln("  						 <li class=\'list-header\'><font size=\'4\'>Other Infomation</font></li>");
document.writeln("  						 ");
document.writeln("  						 <!--Menu list item-->");
document.writeln("  						 <li>");
document.writeln("  						      <a href=\'./datastatistics.html\'>");
document.writeln("  						          <i class=\'fa fa-pie-chart\' style=\'width:24px\'></i>");
document.writeln("  						          <span class=\'menu-title\'>");
document.writeln("  						              <font size=\'3\'><strong>Statistics</strong></font>");
document.writeln("  						          </span>");
document.writeln("  						      </a>");
document.writeln("  						  </li>");
document.writeln("						  <!--Menu list item-->");
document.writeln("						  <li>");
document.writeln("						       <a href=\'./degree.html\'>");
document.writeln("						           <i class=\'fa fa-pie-chart\' style=\'width:24px\'></i>");
document.writeln("						           <span class=\'menu-title\'>");
document.writeln("						               <font size=\'3\'><strong>Degree</strong></font>");
document.writeln("						           </span>");
document.writeln("						       </a>");
document.writeln("						    							   ");
document.writeln("						   </li>");
document.writeln("  						  <!--Menu list item-->");

document.writeln("  			        </ul>");
document.writeln("                  </div>");
document.writeln("              </div>");
document.writeln("          </div>");
document.writeln("          <!--================================-->");
document.writeln("          <!--End menu-->");
document.writeln("  ");
document.writeln("      </div>");
document.writeln("  </nav>");
document.writeln("  <!--===================================================-->");
document.writeln("  <!--END MAIN NAVIGATION-->");
document.writeln("");